package com.zyx.payimooc.dao;

import com.zyx.payimooc.pojo.PayInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_pay_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_pay_info
     *
     * @mbg.generated
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_pay_info
     *
     * @mbg.generated
     */
    int insertSelective(PayInfo record);


    /**
     * 根据订单号查询
     * @param id
     * @return
     */
    PayInfo selectByOrderId(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_pay_info
     *
     * @mbg.generated
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_pay_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_pay_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayInfo record);
}